export const seedState = {
  policyRules: {
    stpLimit: 25000,
    deductible: 2500,
    reviewAmountCap: 50000,
    duplicateSimilarityThreshold: 0.85,
    policyAgeReviewDays: 30,
    toggles: {
      stpThreshold: true,
      deductible: true,
      duplicateCheck: true,
      providerRisk: true,
      docValidation: true,
      amountCap: true,
    },
  },
  users: [
    {
      id: "usr-admin",
      email: "admin@claimswift.ai",
      password: "admin123",
      name: "Asha Rao",
      role: "ops_admin",
      permissions: ["claims:read", "claims:create", "claims:clarify", "claims:review", "claims:settle", "policy:read", "policy:write", "analytics:read", "audit:read", "platform:read"],
    },
    {
      id: "usr-adjuster",
      email: "adjuster@claimswift.ai",
      password: "adjust123",
      name: "Karan Mehta",
      role: "claims_adjuster",
      permissions: ["claims:read", "claims:create", "claims:clarify", "claims:settle", "policy:read", "analytics:read", "platform:read"],
    },
    {
      id: "usr-reviewer",
      email: "reviewer@claimswift.ai",
      password: "review123",
      name: "Neelima Shah",
      role: "fraud_reviewer",
      permissions: ["claims:read", "claims:review", "policy:read", "analytics:read", "audit:read", "platform:read"],
    },
    {
      id: "usr-analyst",
      email: "analyst@claimswift.ai",
      password: "analyst123",
      name: "Dev Khanna",
      role: "ops_analyst",
      permissions: ["claims:read", "policy:read", "analytics:read", "audit:read", "platform:read"],
    },
  ],
  sessions: [],
  auditEvents: [
    {
      id: "audit-seed-1",
      at: "2026-03-15T08:15:00Z",
      actorId: "system",
      actorName: "ClaimSwift bootstrap",
      actorRole: "system",
      action: "platform.seed_loaded",
      entityType: "platform",
      entityId: "runtime-store",
      outcome: "success",
      summary: "Seed data loaded for insurer demo workspace.",
      requestId: "seed-runtime-store",
    },
  ],
  providers: [
    { id: "prov-sunrise", name: "Sunrise Multispeciality Hospital", city: "Pune", registryVerified: true, gstValid: true, riskLevel: "medium" },
    { id: "prov-citycare", name: "CityCare Diagnostics", city: "Mumbai", registryVerified: true, gstValid: true, riskLevel: "low" },
    { id: "prov-rapid", name: "Rapid Auto Garage", city: "Bengaluru", registryVerified: true, gstValid: true, riskLevel: "medium" },
    { id: "prov-safehome", name: "SafeHome Repair Works", city: "Delhi", registryVerified: true, gstValid: true, riskLevel: "low" },
    { id: "prov-lifeassist", name: "LifeAssist Verification Desk", city: "Hyderabad", registryVerified: true, gstValid: true, riskLevel: "low" },
  ],
  claims: [
    {
      id: "CLM-2026-2105",
      insuranceType: "health",
      productLabel: "Health reimbursement",
      claimantName: "Riya Sharma",
      policyHolderName: "Riya Sharma",
      providerId: "prov-sunrise",
      providerName: "Sunrise Multispeciality Hospital",
      city: "Pune",
      procedure: "Day-care treatment reimbursement",
      claimAmount: 22000,
      benchmarkAmount: 12500,
      policyNumber: "POL-HEALTH-8821",
      policyAgeDays: 94,
      incidentDate: "2026-03-10",
      admissionDate: "2026-03-10",
      submittedAt: "2026-03-10T09:20:00Z",
      status: "clarification_required",
      lowConfidenceFields: [
        { field: "invoice_total", value: "INR 12,450 (?)", confidence: 38, source: "invoice" },
        { field: "discharge_date", value: "12 Apr 2026", confidence: 65, source: "bill" }
      ],
      missingDocuments: ["discharge summary"],
      duplicateSimilarity: 0.12,
      providerRiskLevel: "medium",
      documentSignals: {
        editedDocument: false,
        reusedDocument: false,
        totalMismatch: true,
        metadataModified: false,
      },
      crossDocumentMismatches: [
        "Claim amount on form does not match extracted invoice total",
      ],
      explanationSummary: "Extraction confidence is too low to continue safely without claimant confirmation.",
      activities: [
        { title: "Intake agent", status: "done", copy: "Claim package validated — 2 of 3 required documents accepted.", meta: "2s ago" },
        { title: "Extraction agent", status: "done", copy: "8 fields extracted. Invoice total confidence is 38%.", meta: "Low-confidence field" },
        { title: "Clarification agent", status: "waiting", copy: "Discharge summary missing and invoice total needs manual confirmation.", meta: "Action required" },
        { title: "Policy agent", status: "pending", copy: "Eligibility, deductible, and waiting-period checks queued.", meta: "Starts after clarification" },
        { title: "Fraud agent", status: "pending", copy: "Duplicate signals, provider risk, and amount anomalies queued.", meta: "Risk scoring" },
        { title: "Decision agent", status: "pending", copy: "Routing will be prepared after the claimant reply arrives.", meta: "Final step" }
      ],
      timelineNotes: [
        "Claim paused safely because one critical billing field was unreadable.",
        "Claimant receives a clarification prompt instead of silent rejection."
      ],
      reviewNotes: [],
    },
    {
      id: "CLM-2026-2106",
      insuranceType: "health",
      productLabel: "Health reimbursement",
      claimantName: "Aman Verma",
      policyHolderName: "Aman Verma",
      providerId: "prov-citycare",
      providerName: "CityCare Diagnostics",
      city: "Mumbai",
      procedure: "Outpatient diagnostic reimbursement",
      claimAmount: 22000,
      benchmarkAmount: 20500,
      policyNumber: "POL-HEALTH-9033",
      policyAgeDays: 214,
      incidentDate: "2026-03-09",
      admissionDate: "2026-03-09",
      submittedAt: "2026-03-09T12:10:00Z",
      status: "approved_for_stp",
      lowConfidenceFields: [],
      missingDocuments: [],
      duplicateSimilarity: 0.04,
      providerRiskLevel: "low",
      documentSignals: {
        editedDocument: false,
        reusedDocument: false,
        totalMismatch: false,
        metadataModified: false,
      },
      crossDocumentMismatches: [],
      explanationSummary: "All mandatory documents match policy terms and the claim is eligible for straight-through settlement.",
      activities: [
        { title: "Intake agent", status: "done", copy: "Claim package validated — 3 documents accepted.", meta: "Completed" },
        { title: "Extraction agent", status: "done", copy: "All mandatory fields extracted with strong confidence.", meta: "Invoice verified at 91%" },
        { title: "Policy agent", status: "done", copy: "Coverage matched and deductible applied successfully.", meta: "Eligible" },
        { title: "Fraud agent", status: "done", copy: "No duplicate signal or provider anomaly detected.", meta: "Risk score 18/100" },
        { title: "Decision agent", status: "active", copy: "Preparing payout initiation and claimant notification.", meta: "Running now" },
        { title: "Settlement agent", status: "pending", copy: "UPI payout and status notification will be triggered next.", meta: "Final step" }
      ],
      timelineNotes: [
        "Low-risk verified claim routed to straight-through settlement.",
        "Claimant receives payout breakdown before disbursement."
      ],
      reviewNotes: [],
    },
    {
      id: "CLM-2026-2108",
      insuranceType: "health",
      productLabel: "Health reimbursement",
      claimantName: "Neha Kulkarni",
      policyHolderName: "Neha Kulkarni",
      providerId: "prov-sunrise",
      providerName: "Sunrise Multispeciality Hospital",
      city: "Pune",
      procedure: "Hospital admission reimbursement",
      claimAmount: 96000,
      benchmarkAmount: 43000,
      policyNumber: "POL-HEALTH-7710",
      policyAgeDays: 120,
      incidentDate: "2026-03-12",
      admissionDate: "2026-03-12",
      submittedAt: "2026-03-12T08:30:00Z",
      status: "human_review",
      lowConfidenceFields: [],
      missingDocuments: [],
      duplicateSimilarity: 0.91,
      providerRiskLevel: "high",
      documentSignals: {
        editedDocument: true,
        reusedDocument: true,
        totalMismatch: true,
        metadataModified: true,
      },
      crossDocumentMismatches: [
        "Invoice amount does not match discharge summary line items",
        "Doctor name on bill differs from prescription"
      ],
      explanationSummary: "The claim exceeds safe payout thresholds and shows strong duplicate, edit, and provider-risk signals.",
      activities: [
        { title: "Intake agent", status: "done", copy: "High-value claim package validated.", meta: "Completed" },
        { title: "Extraction agent", status: "done", copy: "Invoice, provider, and procedure fields extracted.", meta: "Multiple signals found" },
        { title: "Clarification agent", status: "done", copy: "Claimant confirmed corrected invoice amount.", meta: "Recovery succeeded" },
        { title: "Policy agent", status: "done", copy: "Coverage matched but payout exceeds STP threshold.", meta: "Above safe threshold" },
        { title: "Fraud agent", status: "active", copy: "Strong duplicate invoice similarity and amount outlier detected.", meta: "Reviewer attention needed" },
        { title: "Decision agent", status: "waiting", copy: "Recommendation prepared — awaiting manual approval.", meta: "Waiting for reviewer" }
      ],
      timelineNotes: [
        "Claim routed to manual review because fraud score is above the high-risk band.",
        "Provider anomaly and duplicate evidence both contributed to escalation."
      ],
      reviewNotes: [],
    },
    {
      id: "CLM-2026-3102",
      insuranceType: "motor",
      productLabel: "Motor minor damage",
      claimantName: "Rahul Menon",
      policyHolderName: "Rahul Menon",
      providerId: "prov-rapid",
      providerName: "Rapid Auto Garage",
      city: "Bengaluru",
      procedure: "Rear bumper repair",
      claimAmount: 18200,
      benchmarkAmount: 16000,
      policyNumber: "POL-MOTOR-4431",
      policyAgeDays: 402,
      incidentDate: "2026-03-07",
      admissionDate: null,
      submittedAt: "2026-03-07T16:10:00Z",
      status: "approved_for_stp",
      lowConfidenceFields: [],
      missingDocuments: [],
      duplicateSimilarity: 0.09,
      providerRiskLevel: "medium",
      documentSignals: {
        editedDocument: false,
        reusedDocument: false,
        totalMismatch: false,
        metadataModified: false,
      },
      crossDocumentMismatches: [],
      explanationSummary: "Minor motor damage claim fits the low-risk photo and cost profile for straight-through processing.",
      activities: [],
      timelineNotes: [
        "Damage pattern and repair estimate matched a low-severity bumper impact."
      ],
      reviewNotes: [],
    },
    {
      id: "CLM-2026-4104",
      insuranceType: "home",
      productLabel: "Home contents",
      claimantName: "Priyanka Das",
      policyHolderName: "Priyanka Das",
      providerId: "prov-safehome",
      providerName: "SafeHome Repair Works",
      city: "Delhi",
      procedure: "Water damage repair",
      claimAmount: 64000,
      benchmarkAmount: 51000,
      policyNumber: "POL-HOME-1140",
      policyAgeDays: 36,
      incidentDate: "2026-03-14",
      admissionDate: null,
      submittedAt: "2026-03-14T10:55:00Z",
      status: "verification_queue",
      lowConfidenceFields: [],
      missingDocuments: [],
      duplicateSimilarity: 0.22,
      providerRiskLevel: "low",
      documentSignals: {
        editedDocument: false,
        reusedDocument: false,
        totalMismatch: false,
        metadataModified: false,
      },
      crossDocumentMismatches: [
        "Incident date is close to policy inception"
      ],
      explanationSummary: "Home claim is routed to verification because the policy is still in an early-life review window.",
      activities: [],
      timelineNotes: [
        "Policy age rule triggered mandatory verification."
      ],
      reviewNotes: [],
    },
    {
      id: "CLM-2026-5107",
      insuranceType: "life",
      productLabel: "Life benefit verification",
      claimantName: "Sonal Iyer",
      policyHolderName: "Sonal Iyer",
      providerId: "prov-lifeassist",
      providerName: "LifeAssist Verification Desk",
      city: "Hyderabad",
      procedure: "Nominee benefit validation",
      claimAmount: 150000,
      benchmarkAmount: 150000,
      policyNumber: "POL-LIFE-7712",
      policyAgeDays: 730,
      incidentDate: "2026-03-02",
      admissionDate: null,
      submittedAt: "2026-03-02T11:40:00Z",
      status: "human_review",
      lowConfidenceFields: [],
      missingDocuments: [],
      duplicateSimilarity: 0.01,
      providerRiskLevel: "low",
      documentSignals: {
        editedDocument: false,
        reusedDocument: false,
        totalMismatch: false,
        metadataModified: false,
      },
      crossDocumentMismatches: [],
      explanationSummary: "Life claims remain human-supervised even when document confidence is high because payout criticality is high.",
      activities: [],
      timelineNotes: [
        "Life benefit claims stay in manual review by policy design."
      ],
      reviewNotes: [],
    }
  ],
};
